package org.jesgs.moonphase.ui;

import java.awt.List;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.JLabel;
/**
 *
 * @author Jess Green <jgreen@periscope.com>
 */
public class MoonData extends JPanel {



    private Map<String, String>[] labels = null;
    private JLabel[] jlabels;

    /**
     * Creates new form MoonData
     */
    public MoonData(Map<String, String>[] labels) {
        this.labels = labels;

        setupLabels();
        initComponents();
    }


    public void setupLabels()
    {
        if (labels == null) {
            return;
        }

//        Iterator it = labels.values().iterator();

    }


    public void setLabelData(Map<String, String>[] labels)
    {
        this.labels = labels;
    }



    public Map<String, String>[] getLabelData()
    {
        return labels;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
